language: python

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull satwikbh/python-web-app:1.0
  - docker images

script:
  - docker run -d -p 5000:5000 python-web-app:1.0
