# Set python version to 3.8
FROM python:3.8

# Set working directory in the container
WORKDIR /code

# Copy the requirements.txt file to work dir
COPY requirements.txt .

# Install the dependencies present in requirements.txt
RUN pip install -r requirements.txt

# Copy the code
COPY . .

# Command to run the code
CMD ["python", "python-web-app.py"]